# Generated by Django 4.2 on 2023-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Request for help', 'Request for help'), ('Available', 'Available')], default='Request for help', max_length=100, verbose_name='Request type')),
                ('item_name', models.CharField(choices=[('Food', 'Food'), ('Drinking Water', 'Drinking Water'), ('Medicine', 'Medicine'), ('Transport', 'Transport'), ('Accommodation', 'Accommodation')], max_length=100, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='Water',
        ),
    ]
