# Generated by Django 4.2 on 2023-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0002_request_delete_accommodation_delete_fooditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Request for help', 'Request for help'), ('Available', 'Available')], max_length=100, verbose_name='Request type'),
        ),
    ]
