# Generated by Django 4.2 on 2023-04-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0003_alter_request_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy')], max_length=100, verbose_name='service_name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('open_from', models.DateTimeField(auto_now_add=True, verbose_name='Open From')),
                ('closes_at', models.DateTimeField(auto_now_add=True, verbose_name='Closes At')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Medical Service',
                'verbose_name_plural': 'Medical Services',
            },
        ),
    ]
