# Generated by Django 4.2 on 2023-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0004_medicalservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
