# Generated by Django 4.2 on 2023-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0007_alter_medicalservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='closes_at',
            field=models.DateTimeField(default='Open 24 hours', verbose_name='Closes At'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='open_from',
            field=models.DateTimeField(verbose_name='Open From'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Request help', 'Request for help'), ('Available', 'Available')], max_length=100, verbose_name='Request type'),
        ),
    ]
