# Generated by Django 4.2 on 2023-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0009_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AddField(
            model_name='request',
            name='hospital_or_pharmacy_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='Description'),
        ),
    ]
