# Generated by Django 4.2 on 2023-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0010_alter_request_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='hospital_or_pharmacy_name',
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='hospital_or_pharmacy_name',
            field=models.CharField(default='', max_length=200, verbose_name='hospital_or_pharmacy_name'),
        ),
    ]
