# Generated by Django 4.2 on 2023-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0011_remove_request_hospital_or_pharmacy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='closes_at',
            field=models.DateTimeField(default='Open 24 hours', verbose_name='Closes at'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='hospital_or_pharmacy_name',
            field=models.CharField(default='', max_length=200, verbose_name='Hospital or pharmacy name'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='open_from',
            field=models.DateTimeField(verbose_name='Open from'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='service_name',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy')], max_length=100, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='item_name',
            field=models.CharField(choices=[('Food', 'Food'), ('Drinking Water', 'Drinking Water'), ('Medicine', 'Medicine'), ('Transport', 'Transport'), ('Accommodation', 'Accommodation')], max_length=100, verbose_name='Item name'),
        ),
    ]
