# Generated by Django 4.2 on 2023-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0014_alter_missingperson_last_seen_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='report_type',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], default='Missing', max_length=30, verbose_name='Gender'),
        ),
    ]
