# Generated by Django 4.2 on 2023-04-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0018_alter_missingperson_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last seen date'),
        ),
    ]
