# Generated by Django 4.2 on 2023-04-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_help', '0020_alter_request_item_name_alter_request_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='reported_by',
        ),
    ]
